# Generated by Django 3.2.4 on 2021-06-25 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210625_2230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order_number', 'id']},
        ),
        migrations.RemoveField(
            model_name='lessoncompletion',
            name='course',
        ),
        migrations.AddField(
            model_name='lessoncompletion',
            name='lesson',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='completed_users', to='main.lesson'),
            preserve_default=False,
        ),
    ]
