# Generated by Django 3.2.4 on 2021-06-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_lesson_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ManyToManyField(default=[1], to='main.Category'),
        ),
    ]
