# Generated by Django 3.2.4 on 2021-06-23 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='main.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='order_number',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
